"""Lightweight pure-Python CLI wrapper for AdaSDF-CL tools."""

from __future__ import annotations

from .config import AdaSDFConfig, default_config, find_tool
from .exceptions import AdaSDFCommandError, AdaSDFError, AdaSDFParseWarning, AdaSDFToolNotFound
from .results import (
    ActiveBlockQueryResult,
    ActiveBlockSelectionResult,
    BenchmarkResult,
    BlockCacheBenchmarkResult,
    BuildResult,
    CollisionResult,
    CommandResult,
    ContactCandidatesResult,
    CudaActiveBlockQueryResult,
    CudaBlockCacheBenchmarkResult,
    InfoResult,
    MeshCheckResult,
    QueryResult,
    RecommendationResult,
    SparseBenchmarkResult,
    SparseCollisionResult,
    SparseQueryResult,
)
from .tools import (
    active_block_query,
    benchmark_batch_query,
    benchmark_block_cache,
    benchmark_builder_acceleration,
    benchmark_cuda_block_cache,
    benchmark_sparse_query,
    build_adaptive_sdf,
    build_compressed_sdf,
    build_dense_sdf,
    capabilities,
    collide,
    compress_adaptive_sdf,
    contact_candidates,
    cuda_active_block_query,
    expansion_quality,
    info,
    mesh_check,
    mesh_clean,
    query,
    recommend_build,
    select_active_blocks,
    sparse_collide,
    sparse_query,
)
from .workflows import preprocess_and_build_compressed, recommend_then_build_compressed

__version__ = "1.12.0-alpha"

__all__ = [
    "AdaSDFConfig",
    "AdaSDFCommandError",
    "AdaSDFError",
    "AdaSDFParseWarning",
    "AdaSDFToolNotFound",
    "ActiveBlockQueryResult",
    "ActiveBlockSelectionResult",
    "BenchmarkResult",
    "BlockCacheBenchmarkResult",
    "BuildResult",
    "CollisionResult",
    "CommandResult",
    "ContactCandidatesResult",
    "CudaActiveBlockQueryResult",
    "CudaBlockCacheBenchmarkResult",
    "InfoResult",
    "MeshCheckResult",
    "QueryResult",
    "RecommendationResult",
    "SparseBenchmarkResult",
    "SparseCollisionResult",
    "SparseQueryResult",
    "active_block_query",
    "benchmark_batch_query",
    "benchmark_block_cache",
    "benchmark_builder_acceleration",
    "benchmark_cuda_block_cache",
    "benchmark_sparse_query",
    "build_adaptive_sdf",
    "build_compressed_sdf",
    "build_dense_sdf",
    "capabilities",
    "collide",
    "compress_adaptive_sdf",
    "contact_candidates",
    "cuda_active_block_query",
    "default_config",
    "expansion_quality",
    "find_tool",
    "info",
    "mesh_check",
    "mesh_clean",
    "preprocess_and_build_compressed",
    "query",
    "recommend_build",
    "recommend_then_build_compressed",
    "select_active_blocks",
    "sparse_collide",
    "sparse_query",
]
